# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmModel',
            fields=[
                ('tag', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='Name/Tag')),
                ('severity', models.CharField(blank=True, choices=[('ALARM', 'ALARM'), ('WARNING', 'WARNING'), ('INFO', 'INFO'), ('ERROR', 'ERROR'), ('DEBUG', 'DEBUG')], max_length=128, verbose_name='Severity')),
                ('state', models.CharField(blank=True, choices=[('NORM', 'Not active'), ('UNACK', 'Active, not acknowledged'), ('RTNUN', 'Activated but condition return to normal'), ('ACKED', 'Active, acknowledged'), ('OOSRV', 'Active, not acknowledged'), ('ERROR', 'Error'), ('UNACK', 'Active, not acknowledged'), ('DSUPR', 'DSUPR'), ('SHLVD', 'SHLVD')], max_length=128, verbose_name='State')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('formula', models.TextField(blank=True, verbose_name='Formula')),
                ('receivers', models.TextField(blank=True, verbose_name='Receivers')),
                ('wiki_link', models.URLField(blank=True, verbose_name='WiKi')),
                ('device', models.CharField(blank=True, max_length=255, verbose_name='PyAlarm device')),
                ('is_disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('activation_time', models.DateTimeField(blank=True, verbose_name='Activation time')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmsSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_alarms_update', models.DateTimeField()),
                ('update_period', models.DurationField()),
            ],
        ),
    ]
