# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tango_panicapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmmodel',
            name='activation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Activation time'),
        ),
    ]
