# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_tango_panicapi', '0002_auto_20180611_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('comment', models.TextField()),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='django_tango_panicapi.AlarmModel')),
            ],
        ),
        migrations.AddField(
            model_name='alarmssettings',
            name='last_history_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='alarmssettings',
            name='last_alarms_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
